authors/urls.py
# Django
from django.urls import include, path

# Views
from . import views
from authors.views import api

# Rest Framework
from rest_framework.routers import SimpleRouter

app_name = 'authors'

author_api_router = SimpleRouter()
author_api_router.register('', api.AuthorViewSet, basename='author-api')


urlpatterns = [
    # Register
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    # Login
    path('login/', views.login_view, name='login'),
    path('login/create', views.login_create, name='login_create'),
    # Logout
    path('logout/', views.logout_view, name='logout'),
    # Dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/recipe/new/', views.DashboardRecipeCreate.as_view(), name='dashboard_recipe_new'),
    path('dashboard/recipe/delete/', views.DashboardRecipeDelete.as_view(), name='dashboard_recipe_delete'),
    path('dashboard/recipe/<int:id>/edit/', views.DashboardRecipeEdit.as_view(), name='dashboard_recipe_edit'),
    # Profile
    path('profile/<int:id>', views.ProfileView.as_view(), name='profile'),

    # API - View Set
    path('api/', include(author_api_router.urls)),
]   

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from recipes.views import home
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
# Django
from django.urls import include, path

# Views
from .views import site
from .views import api

# JWT
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

# Rest Framework
from rest_framework.routers import SimpleRouter

app_name = 'recipes'

recipe_api_v2_router = SimpleRouter()
recipe_api_v2_router.register('', api.RecipeAPIv2ViewSet, basename='recipes-api')

urlpatterns = [
    path('', site.RecipeListViewHome.as_view(), name='home'),
    path('recipes/search/', site.RecipeListViewSearch.as_view(), name='search'),  # type: ignore
    path('recipes/category/<int:category_id>/', site.RecipeListViewCategory.as_view(), name='category'),
    path('recipes/<int:pk>/', site.RecipeDetailViewBase.as_view(), name='recipe'),
    
    # API - V1
    path('recipes/api/v1', site.RecipeListViewHomeApi.as_view(), name='recipe_api'),
    path('recipes/api/v1/<int:pk>', site.RecipeDetailAPI.as_view(), name='recipe_api_v1_detail'),
    
    # Teoria
    path('recipes/theory/', site.theory, name='theory'),
    
    # Tag
    path('recipes/tags/<slug:slug>', site.RecipeListViewTag.as_view(), name='tags'),
    
    # JWT Authentication
    path('recipes/api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('recipes/api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('recipes/api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

    # API - V2
    path('recipes/api/v2/', include(recipe_api_v2_router.urls)),
    path('recipes/api/v2/tag/<int:pk>/', api.TagAPIV2Detail.as_view(), name='recipe_api_v2_tag'),
]

authors/forms/recipe_forms.py
from django import forms
from recipes.models import Recipe
from utils.django_forms import add_attr
from utils.strings import is_positive_number
from collections import defaultdict
from django.core.exceptions import ValidationError
from authors.validators import AuthorRecipeValidator

# Formulário de receitas (edição)
class AuthorRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) # Inicia classe pai, antes da classe filha(AuthorRecipeForm)

        self._my_errors = defaultdict(list)

        # Estilizando diretamente campos do formulário
        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')

    class Meta: # Configurações adicionais deste formulário - metadados
        model = Recipe # Modelo que o formulário está associado
        fields = ('title',  # Quais campos do modelo serão incluídos no formulário 
                  'description', 'preparation_time', 'preparation_time_unit',
                  'servings', 'servings_unit', 'preparation_steps','cover', 'category'
        )
        # Customização e comportamento do elemento (campos do form) para interface de usuário
        widgets = { 
            'cover': forms.FileInput( # Widget usado para campos de arquivo
                attrs={
                    'class': 'span-2'
                }
            ),
            'servings_unit': forms.Select( # Widget usado para campos de escolha
                choices=( # Escolhas
                    ('Porções', 'Porções'),
                    ('Pedaços', 'Pedaços'),
                    ('Pessoas', 'Pessoas'),
                )
            ),
            'preparation_time_unit': forms.Select( # Widget usado para campos de escolha
                choices=( # Escolhas
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                )
            )
        }

    # Limpando dados do formulário
    def clean(self):
        super_clean = super().clean() # Garantindo que a validação da classe pai seja mantida
        
        AuthorRecipeValidator(self.cleaned_data, ErrorClass=ValidationError)

        return super_clean

recipes/views.py
# Models Manipulation
from django.db.models.aggregates import Count
from django.db.models.query import QuerySet
from recipes.models import Recipe, Category
from django.db.models import Q, F, Value
from django.forms.models import model_to_dict
from django.db.models.functions import Concat
from tag.models import Tag

from typing import Any
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render, get_list_or_404, get_object_or_404
from utils.pagination import make_pagination
from utils.recipes.factory import make_recipe
from django.http import Http404, HttpRequest, HttpResponse, HttpResponse as HttpResponse, JsonResponse
from django.core.paginator import Paginator
import os
from django.views.generic import ListView, DetailView

PER_PAGE = int(os.environ.get('PER_PAGE', 9))

class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs) -> QuerySet[Recipe]:
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
        )
        qs = qs.prefetch_related('author', 'category')
        qs = qs.prefetch_related('tags', 'author__profile')
        
        return qs
    
    def get_context_data(self, *args, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(self.request, ctx.get('recipes'),PER_PAGE)
        ctx.update({
            'recipes': page_obj,
            'pagination_range': pagination_range
        })

        return ctx


class RecipeListViewHome(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'

# ListView API
class RecipeListViewHomeApi(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'

    def render_to_response(self, context: dict[str, Any], **response_kwargs: Any) -> HttpResponse:
        recipe = self.get_context_data()['recipes']
        recipe_list = list(recipe.object_list.values())

        return JsonResponse(
            recipe_list,
            safe=False
        )    


class RecipeListViewCategory(RecipeListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_queryset(self, *args, **kwargs) -> QuerySet[Recipe]:
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            category__id=self.kwargs['category_id'],
            is_published=True
        )

        if not qs:
            raise Http404()

        return qs
    
    def get_context_data(self, *args, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(*args, **kwargs)
        object_list = ctx['object_list']
        category_name = object_list[0].category.name
        
        ctx.update({
            'title': f'{category_name} - Category |'
        })
        return ctx


class RecipeListViewSearch(RecipeListViewBase):
    template_name = 'recipes/pages/search.html'

    def get_search_term(self):
        search_term = self.request.GET.get('q', '')
        return str(search_term)

    def get_queryset(self, *args, **kwargs) -> QuerySet[Recipe]:
        qs = super().get_queryset(*args, **kwargs)
        search_term = self.get_search_term()
        
        if not search_term:
            raise Http404()

        qs = qs.filter(
            Q(
                Q(title__icontains=search_term) | 
                Q(description__icontains=search_term)
            ),
            is_published=True,
        ).order_by('-id')

        return qs 

    def get_context_data(self, *args, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.get_search_term()
        
        
        ctx.update({
            'page_title': f'Search for "{search_term}"',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        })

        return ctx


class RecipeDetailViewBase(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe-view.html'

    def get_queryset(self) -> QuerySet[Recipe]:
        qs = super().get_queryset()
        qs = qs.filter(
            is_published=True
        )

        return qs

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        
        ctx.update({
            'is_detail_page': True
        })
        
        return ctx
    
# DetailView API
class RecipeDetailAPI(RecipeDetailViewBase):
    def render_to_response(self, context: dict[str, Any], **response_kwargs: Any) -> HttpResponse:
        recipe = self.get_context_data()['recipe']
        recipe_dict = model_to_dict(recipe)

        recipe_dict['created_at'] = recipe.created_at
        recipe_dict['updated_at'] = recipe.updated_at

        if recipe_dict.get('cover'):
            recipe_dict['cover'] = recipe_dict['cover'].url
        else:
            recipe_dict['cover'] = ''

        del recipe_dict['is_published']
        del recipe_dict['preparation_steps_is_html']

        return JsonResponse(
            recipe_dict,
            safe=False
        )
    

# Teoria
def theory(request, *args, **kwargs):

    # Consulta
    recipes = Recipe.my_manager.get_published()

    context = {
        'recipes': recipes
    }

    return render(
        request, 
        'recipes/pages/theory.html',
        context=context,
    )


class RecipeListViewTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs) -> QuerySet[Recipe]:
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))

        return qs

    def get_context_data(self, *args, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(slug=self.kwargs.get('slug', '')).first()
        
        if not page_title:
            page_title = 'No recipes found'
        page_title = f'{page_title} - Tag'
        
        ctx.update({
            'page_title': page_title,
        })

        return ctx

recipes/views/api.py
# Django
from django.shortcuts import get_object_or_404
from ..permissions import IsOwner

# Rest Framework
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.pagination import PageNumberPagination
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticatedOrReadOnly

# Models
from ..models import Recipe
from tag.models import Tag
from ..serializers import RecipeSerializer, TagSerializer


# Paginação
class RecipeAPIV2Pagination(PageNumberPagination):
    page_size = 5


# View Set - Listagem, Criação e Detalhes tudo junto
class RecipeAPIv2ViewSet(ModelViewSet):
    queryset = Recipe.my_manager.get_published()
    serializer_class = RecipeSerializer
    pagination_class = RecipeAPIV2Pagination
    permission_classes = [IsAuthenticatedOrReadOnly]
    http_method_names = ['get', 'options', 'head', 'patch', 'post', 'delete']

    # Lista
    def get_object(self):
        pk = self.kwargs.get('pk', '')
        obj = get_object_or_404(
            self.get_queryset(),
            pk=pk
        )

        self.check_object_permissions(self.request, obj)

        return obj
    
    # Permite
    def get_permissions(self):
        if self.request.method in ['PATCH', 'DELETE']:
            return [IsOwner(), ]

        return super().get_permissions()
    
    # Cria
    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(author=request.user)
        headers = self.get_success_headers(serializer.data)

        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
    
    # Atualiza
    def partial_update(self, request, *args, **kwargs):
        recipe = self.get_object()
        serializer = RecipeSerializer(
            instance=recipe,
            data=request.data,
            many=False,
            context={'request': request},
            partial=True
        )
        serializer.is_valid()
        serializer.save()

        return Response(serializer.data)
    

# Detalhes
class TagAPIV2Detail(APIView):
    def get(self, request, pk):
        tag = get_object_or_404(Tag.objects.filter(pk=pk))
        serializer = TagSerializer(
            instance=tag,
            many=False,
            context={'request': request}
        )

        return Response(serializer.data)
    

recipes/templates/recipes/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&family=Titillium+Web:wght@300&display=swap"
        rel="stylesheet">
      
        <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'global/css/global_style.css' %}">

     

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">

    {% if recipe.cover %}
    <div class="recipe-cover">
        <a href="{{ recipe.get_absolute_url }}">
            <img src="{{ recipe.cover.url }}" alt="Temporario">
        </a>
    </div>
    {% endif %}

    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <!-- Usando url absoluta da própria Recipe -->
            <a href="{{ recipe.get_absolute_url }}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">

        {% if recipe.author is not None %}
        <span class="recipe-author-item">

            {% if recipe.author.profile %}
            <a href="{% url 'authors:profile' recipe.author.profile.id %}">
                {% endif %}

                <i class="fas fa-user"></i>
                <!--
                    Se autor tiver nome, exibe o nome e sobrenome normalmente
                    Se não, vai exibir o campo username do Django Admin
                -->
                {% if recipe.author.first_name %}
                {{ recipe.author.first_name }}
                {{ recipe.author.last_name }}
                {% else %}
                {{ recipe.author.username }}
                {% endif %}

                {% if recipe.author.profile %}
            </a>
            {% endif %}
        </span>
        {% else %}
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            Autor desconhecido
        </span>

        {% endif %}

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
        </span>

        {% if recipe.category is not None %}
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span> {{ recipe.category.name }} </span>
            </a>
        </span>
        {% endif %}

    </div>

    <div class="recipe-content">
        <p> {{ recipe.description }} </p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }}
                {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }}
                {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    <!--
        Aqui a variável é TRUE, e o bloco footer, só aparece
        se não for TRUE.
    -->
    {% if not is_detail_page %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
    {% if recipe.preparation_steps_is_html is True %}
    <div class="preparation-steps">
        {{ recipe.preparation_steps|safe }}
    </div>
    {% else %}
    <div class="preparation-steps">
        {{ recipe.preparation_steps|linebreaksbr }}
    </div>
    {% endif %}

    {% if recipe.tags.all %}
    {% for tag in recipe.tags.all %}
    <p>
        Tags:
        <a href="{% url 'recipes:tags' tag.slug %}"> {{ tag.name }} </a>
    </p>
    {% endfor %}
    {% endif %}

    {% endif %}
</div>