authors/urls.py
# Django
from django.urls import include, path

# Views
from . import views
from authors.views import api

# Rest Framework
from rest_framework.routers import SimpleRouter

app_name = 'authors'

author_api_router = SimpleRouter()
author_api_router.register('', api.AuthorViewSet, basename='author-api')


urlpatterns = [
    # Register
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    # Login
    path('login/', views.login_view, name='login'),
    path('login/create', views.login_create, name='login_create'),
    # Logout
    path('logout/', views.logout_view, name='logout'),
    # Dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/recipe/new/', views.DashboardRecipeCreate.as_view(), name='dashboard_recipe_new'),
    path('dashboard/recipe/delete/', views.DashboardRecipeDelete.as_view(), name='dashboard_recipe_delete'),
    path('dashboard/recipe/<int:id>/edit/', views.DashboardRecipeEdit.as_view(), name='dashboard_recipe_edit'),
    # Profile
    path('profile/<int:id>', views.ProfileView.as_view(), name='profile'),

    # API - View Set
    path('api/', include(author_api_router.urls)),
]   

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from recipes.views import home
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Profile(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)  # RELAÇÃO
    bio = models.TextField(default='', blank=True)

authors/forms/login.py
from django import forms
from utils.django_forms import add_placeholder

class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Type your username')
        add_placeholder(self.fields['password'], 'Type your password')

    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

authors/views.py
from django.urls import reverse
from django.http import Http404
from django.shortcuts import redirect, render
from authors.forms import RegisterForm, LoginForm, AuthorRecipeForm
from pprint import pprint
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from recipes.models import Recipe

# Create your views here.
def register_view(request):
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)

    return render(request, 'authors/pages/register_view.html',
        {
            'form': form,
            'form_action': reverse('authors:register_create')
        }
    )

# View responsável somente por TRATAR os DADOS do FORMULÁRIO
def register_create(request):
    if not request.POST:
        raise Http404

    POST = request.POST  # QueryDict com os dados de cada campo do formulário
    request.session['register_form_data'] = POST # Armazenando dados do formulário em uma chave da sessão.
    form = RegisterForm(POST)

    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password) # Salva um password criptografado no BD
        user.save()

        messages.success(request, 'Yor user is created! Please log in.')

        del(request.session['register_form_data'])
        return redirect('authors:login')

    return redirect('authors:register')

def login_view(request):
    form = LoginForm()

    return render(request, 'authors/pages/login.html', 
        {
            'form': form,
            'form_action': reverse('authors:login_create')
        }
    )

def login_create(request):
    
    form = LoginForm(request.POST)
    login_url = reverse('authors:login')

    # Autenticando usuário
    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )

        if authenticated_user is not None:
            messages.success(request, 'Login successfully!')
            login(request, authenticated_user) 
        else:
            messages.error(request, 'Invalid credentials.')
    else:
        messages.error(request, 'Error to validate form data.')

    return redirect(reverse('authors:dashboard'))

@login_required(login_url='authors:login', redirect_field_name='next') # Precisa estar logado para que a view funcione.
def logout_view(request):
    # Tentativa de logout sem estar logado, ou por meio de GET, gera mensagem de erro e Http404
    if not request.POST:
        messages.error(request, 'Invalid logout request')
        raise Http404()
    
    # Redireciona o usuário que tente fazer logout com credenciais diferentes das do usuário atualmente autenticado
    if request.POST.get('username') != request.user.username:
        messages.error(request, 'Invalid logout user')
        return redirect(reverse('authors:login'))
    
    # Se estiver tudo válido, mostra mensagem de logout feito com sucesso
    messages.success(request, 'Logged out successfully')

    # Remove a identificação do usuário autenticado do objeto request e 
    # também remove os dados da sessão associados a esse usuário. O usuário é "desconectado" do sistema.
    logout(request)

    return redirect(reverse('authors:login'))

# View dashboard - área admin do autor
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard(request):
    # Pegando receitas de um usuário específico e não publicadas
    recipes = Recipe.objects.filter(
        is_published=False, # Receitas não publicadas.
        author=request.user # Dono da receita deve ser o mesmo que está logado no site
    )

    return render(request, 'authors/pages/dashboard.html', 
        {
            'recipes': recipes,
        }
    )

# View para edição da receita
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_edit(request, id):
    # Buscando receita do usuário
    recipe = Recipe.objects.filter(
        is_published=False,
        author=request.user,
        pk=id
    )

    # Se não existir receita
    if not recipe:
        messages.error(request, 'You do not have recipe for editing')
        raise Http404
    
    # Formulário recebendo dados para atualização
    form = AuthorRecipeForm(
        data=request.POST or None, # Modelo Form recebe dados postados pelo usuário
        files=request.FILES or None, # Habilitado recebimento de arquivos no form.
        instance=recipe.first() # Pré-preenche os campos do formulário com os valores existentes da instância específica. E os atualiza em sequência
    )

    # Validação do formulário
    if form.is_valid():
        recipe = form.save(commit=False) # Permite ajustes adicionais antes de salvar definitivamente

        recipe.author = request.user  # Autor da receita, tem que ser o usuário logado
        recipe.preparation_steps_is_html = False # Usuário nunca poderá inserir HTML
        recipe.is_published = False # Receita nunca vai ser publicada, de primeiro momento

        # Salvando definitivamente as alterações no modelo (base de dados).
        recipe.save()

        # Feedback pro usuário
        messages.success(request, 'Your recipe has been saved successfully!')

        return redirect(reverse('authors:dashboard_recipe_edit', args=(id, )))

    return render(request, 'authors/pages/dashboard_recipe.html', 
        {
            'form': form
        }
    )

# View para criação de nova receita
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_create(request):
    form = AuthorRecipeForm(  # Formulário de nova receita já recebendo os dados submetidos
        request.POST or None, 
        files=request.FILES or None,
    )

    # Validação e salvamento dos dados do form no banco de dados
    if form.is_valid():
        new_recipe: Recipe = form.save(commit=False)

        new_recipe.author = request.user # Vinculando o usuário logado, como autor da nova receita
        new_recipe.preparation_steps_is_html = False
        new_recipe.is_published = False

        new_recipe.save() # Salvando definitivamente a nova receita no banco de dados
        
        messages.success(request, 'Your new recipe has been created successfully!') # Feedback pro usuário

        return redirect(reverse('authors:dashboard')) # Redirecionando para dashboard de receitas pós cadastro de nova receita

    # Renderizando o template com contexto
    return render(request, 'authors/pages/dashboard_recipe_create.html', 
        {
            'form': form
        }              
    )

# View para deleção de receita
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_delete(request):
    # Requisição só pode ser POST, caso contrário enviará erros para usuário
    if not request.POST:
        raise Http404
    
    # Pegando ID da receita a ser deletada
    recipe_id = request.POST.get('id')

    # Busca a receita especifica
    recipe = Recipe.objects.filter(
        is_published=False,
        author=request.user,
        pk=recipe_id
    ).first()

    if not recipe: # Se não encontrar a receita, lança um 404
        raise Http404
    
    recipe.delete() # Se encontrar a receita, deleta.
    messages.success(request, 'Deleted successfuly!') # Feedback para usuário, receita deletada!

    return redirect(reverse('authors:dashboard')) # Após a ação, usuário volta para dashboard 

authors/views/all.py
from django.urls import reverse
from django.http import Http404
from django.shortcuts import redirect, render
from authors.forms import RegisterForm, LoginForm, AuthorRecipeForm
from pprint import pprint
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from recipes.models import Recipe

# Create your views here.
def register_view(request):
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)

    return render(request, 'authors/pages/register_view.html',
        {
            'form': form,
            'form_action': reverse('authors:register_create')
        }
    )

# View responsável somente por TRATAR os DADOS do FORMULÁRIO
def register_create(request):
    if not request.POST:
        raise Http404

    POST = request.POST  # QueryDict com os dados de cada campo do formulário
    request.session['register_form_data'] = POST # Armazenando dados do formulário em uma chave da sessão.
    form = RegisterForm(POST)

    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password) # Salva um password criptografado no BD
        user.save()

        messages.success(request, 'Yor user is created! Please log in.')

        del(request.session['register_form_data'])
        return redirect('authors:login')

    return redirect('authors:register')

def login_view(request):
    form = LoginForm()

    return render(request, 'authors/pages/login.html', 
        {
            'form': form,
            'form_action': reverse('authors:login_create')
        }
    )

def login_create(request):
    
    form = LoginForm(request.POST)
    login_url = reverse('authors:login')

    # Autenticando usuário
    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )

        if authenticated_user is not None:
            messages.success(request, 'Login successfully!')
            login(request, authenticated_user) 
        else:
            messages.error(request, 'Invalid credentials.')
    else:
        messages.error(request, 'Error to validate form data.')

    return redirect(reverse('authors:dashboard'))

@login_required(login_url='authors:login', redirect_field_name='next') # Precisa estar logado para que a view funcione.
def logout_view(request):
    # Tentativa de logout sem estar logado, ou por meio de GET, gera mensagem de erro e Http404
    if not request.POST:
        messages.error(request, 'Invalid logout request')
        raise Http404()
    
    # Redireciona o usuário que tente fazer logout com credenciais diferentes das do usuário atualmente autenticado
    if request.POST.get('username') != request.user.username:
        messages.error(request, 'Invalid logout user')
        return redirect(reverse('authors:login'))
    
    # Se estiver tudo válido, mostra mensagem de logout feito com sucesso
    messages.success(request, 'Logged out successfully')

    # Remove a identificação do usuário autenticado do objeto request e 
    # também remove os dados da sessão associados a esse usuário. O usuário é "desconectado" do sistema.
    logout(request)

    return redirect(reverse('authors:login'))

# View dashboard - área admin do autor
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard(request):
    # Pegando receitas de um usuário específico e não publicadas
    recipes = Recipe.my_manager.get_published().filter(author=request.user)

    return render(request, 'authors/pages/dashboard.html', 
        {
            'recipes': recipes,
        }
    )

# View para deleção de receita
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_delete(request):
    # Requisição só pode ser POST, caso contrário enviará erros para usuário
    if not request.POST:
        raise Http404
    
    # Pegando ID da receita a ser deletada
    recipe_id = request.POST.get('id')

    # Busca a receita especifica
    recipe = Recipe.objects.filter(
        is_published=False,
        author=request.user,
        pk=recipe_id
    ).first()

    if not recipe: # Se não encontrar a receita, lança um 404
        raise Http404
    
    recipe.delete() # Se encontrar a receita, deleta.
    messages.success(request, 'Deleted successfuly!') # Feedback para usuário, receita deletada!

    return redirect(reverse('authors:dashboard')) # Após a ação, usuário volta para dashboard 

authors/views/api.py
# Django
from django.shortcuts import get_object_or_404
from recipes.permissions import IsOwner

# Rest Framework
from rest_framework.response import Response
from rest_framework.decorators import action
from rest_framework.pagination import PageNumberPagination
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from rest_framework.permissions import IsAuthenticated

# Models
from ..models import Profile, User
from ..serializers import AuthorSerializer


# View Set - Criação, Listagem, Atualização e Deleção tudo junto
class AuthorViewSet(ReadOnlyModelViewSet):
    serializer_class = AuthorSerializer
    permission_classes = [IsAuthenticated, ]

    def get_queryset(self):
        qs = User.objects.filter(username=self.request.user.username) # type: ignore
        
        return qs
    

    @action(methods=['get'], detail=False)
    def me(self, request, *args, **kwargs):
        obj = self.get_queryset().first()
        serializer = self.get_serializer(
            instance=obj,
        )

        return Response(serializer.data)

authors/views/profile.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from authors.models import Profile

class ProfileView(TemplateView):
    template_name = 'authors/pages/profile.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        profile_id = context.get('id')

        profile = get_object_or_404(
            Profile.objects.filter(pk=profile_id).select_related('author'), 
            pk=profile_id
        )

        return self.render_to_response({
            **context,
            'profile': profile
        })

authors/templates/authors/pages/dashboard.html
{% extends 'global/base.html' %}

{% block title %}Dashboard ({{ user }}) | {% endblock title %}

{% block content %}

  <div class="main-content center container" style="margin-top: 50px;">
    <h2>Dashboard ({{ user }})</h2>
    <!-- Mensagem informativa de login e link para logout do usuário -->
    {% include 'authors/partials/login_message.html'%}
    <!-- Incluindo mensagens de feedback -->
    {% include 'global/partials/messages.html'%}

    <!-- Exibição das receitas do usuário logado -->
    <div class="authors-dashboard-container">
      <h3>Your recipes</h3>
      <!-- Receitas -->
      <ul>
        {% for recipe in recipes %}
          <li>
            <!-- Ao clicar no título da receita, redireciona para página de edição dela -->
            <a href="{% url 'authors:dashboard_recipe_edit' recipe.id %}"> {{ recipe.title }} </a>
            
            <!-- Deletar receitas -->
              <form action="{% url 'authors:dashboard_recipe_delete' %}" class="inline-form form-delete" method="POST">
                {% csrf_token %}
                <!-- Campo escondido recebe o id da receita no loop atual em específico-->
                <input type="hidden" name="id" value="{{ recipe.id }}">
                <button class="plaintext-button" type="submit">❌</button>
              </form>
            <!-- Deletar receitas -->

          </li>
        {% empty %}
          <li>
            <p>You do not have recipes, please create one.</p>
          </li>
        {% endfor %}
      </ul>

    </div>
  </div>
{% endblock content %}

authors/templates/authors/pages/dashboard_recipe.html
{% extends 'global/base.html' %}

{% block title %}Dashboard Recipe | {% endblock title %}

{% block content %}
  {% block search_bar %}{% endblock search_bar%}
  <div class="main-content center container" style="margin-top: 50px;">
    <h2>Dashboard Recipe</h2>
    <!-- Incluindo mensagens de feedback -->
    {% include 'global/partials/messages.html'%}
  
    <!-- Mensagem informativa de login, e link para logout do usuário -->
    {% include 'authors/partials/login_message.html'%}
  
    <!-- Form para editar receita -->
    <div class="left">  
      {% include 'global/partials/form.html'%}
    </div>

  </div>

  
{% endblock content %}

authors/templates/authors/pages/dashboard_recipe_create.html
{% extends 'global/base.html' %}

{% block title %}Dashboard Recipe | {% endblock title %}

{% block content %}

  {% block search_bar %}{% endblock search_bar %}

  <div class="main-content center container" style="margin-top: 50px;">
    <h2>Dashboard Recipe</h2>
    <!-- Incluindo mensagens de feedback -->
    {% include 'global/partials/messages.html'%}
  
    <!-- Mensagem informativa de login, e link para logout do usuário -->
    {% include 'authors/partials/login_message.html'%}
  
    <!-- Form para criar receita -->
    <div class="left">  
      {% include 'global/partials/form.html'%}
    </div>

  </div>

  
{% endblock content %}

authors/templates/authors/pages/login.html
{% extends 'global/base.html' %}

{% block title %}Login | {% endblock title %}

{% block content %}
  {% block search_bar %}{% endblock search_bar %}

  <div class="main-content center container" style="margin-top: 50px;">
    <h2>Login</h2>
    <!-- Mensagem descritiva de usuário logado e link para logout -->
    {% include 'authors/partials/login_message.html'%}
  </div>

  <!-- Incluindo mensagens de feedback para usuário neste template -->
  {% include 'global/partials/messages.html'%}
  
  <!-- Mostra o FORM se usuário não estiver authenticado -->
  {% if not user.is_authenticated %}
    {% include 'global/partials/form.html' %}
  {% endif %}

{% endblock content %}

authors/templates/authors/pages/profile.html
{% extends 'global/base.html' %}

{% block title %}Profile | {% endblock title %}

{% block content %}

<div class="main-content center container" style="margin-top: 50px;">
  <h2> {{ profile.author.username }} </h2>
  <p> {{ profile.bio }} </p>
</div>

{% endblock content %}

authors/templates/authors/pages/register_view.html
{% extends 'global/base.html' %}

{% block title %}Register | {% endblock title %}

{% block content %}
  
  {% block search_bar %}{% endblock search_bar %}

  <div class="main-content center container" style="margin-top: 50px;">
    <h2>Register</h2>
  </div>

  {% include 'global/partials/messages.html'%}

  {% include 'global/partials/form.html'%}
  
{% endblock content %}